language: rust
cache: cargo
rust:
  - stable
services:
  - docker
env:
  - PATH="${PATH}:/tmp/flatbuffers/bin"
before_install:
  - sudo apt update
  - sudo apt install -y libfuse-dev python-xattr
  - git clone https://github.com/google/flatbuffers -b v1.10.0 /tmp/flatbuffers
  - cd /tmp/flatbuffers
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
  - make -j2 flatc
  - mkdir bin
  - mv flatc bin/
  - cd $TRAVIS_BUILD_DIR
before_script:
  - cargo install --force cargo-deny --locked
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo build
  - make test
