FROM ubuntu:18.04

RUN apt update && apt install -y git build-essential autoconf curl cmake libfuse-dev pkg-config fuse bc libtool \
  uuid-dev xfslibs-dev libattr1-dev libacl1-dev libaio-dev

RUN echo 'user_allow_other' >> /etc/fuse.conf

RUN mkdir -p /code/pjdfstest && cd /code && git clone https://github.com/fleetfs/pjdfstest && cd pjdfstest \
  && git checkout f408a711e92c5016a6cf0c6b5555e1d3dde86f1f && autoreconf -ifs && ./configure && make pjdfstest

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain=1.39.0

RUN cd /code && git clone https://github.com/google/flatbuffers && cd flatbuffers && git checkout v1.11.0 \
  && cmake -G "Unix Makefiles" && make flatc && cp flatc /bin/flatc

RUN mkdir -p /code && cd /code && git clone https://github.com/fleetfs/fuse-xfstests && cd fuse-xfstests \
  && git checkout 541c649711b4e09374e3e178fed6effb4aac8423 && make

ADD . /code/fleetfs/

ENV PATH=/root/.cargo/bin:$PATH
