FROM ubuntu:18.04

RUN apt update && apt install -y git build-essential autoconf curl cmake libfuse-dev pkg-config fuse bc libtool \
  uuid-dev xfslibs-dev libattr1-dev libacl1-dev libaio-dev attr acl quota

RUN adduser --disabled-password --gecos '' fsgqa

RUN echo 'user_allow_other' >> /etc/fuse.conf

RUN mkdir -p /code/pjdfstest && cd /code && git clone https://github.com/fleetfs/pjdfstest && cd pjdfstest \
  && git checkout 384af76f2bf0e258a9db3e6eca493491fa09b421 && autoreconf -ifs && ./configure && make pjdfstest

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain=1.42.0

RUN cd /code && git clone https://github.com/google/flatbuffers && cd flatbuffers && git checkout v1.11.0 \
  && cmake -G "Unix Makefiles" && make flatc && cp flatc /bin/flatc

RUN mkdir -p /code && cd /code && git clone https://github.com/fleetfs/fuse-xfstests && cd fuse-xfstests \
  && git checkout 5993a99a16e2547fd00b5fda733bb35aed10e336 && make

ADD . /code/fleetfs/

ENV PATH=/root/.cargo/bin:$PATH
